# Generated by Django 5.1.6 on 2025-03-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("age", models.PositiveIntegerField()),
                ("est_inscrit", models.BooleanField(default=True)),
                (
                    "metiers",
                    models.CharField(
                        choices=[("APD", "APD"), ("DBE", "DBE"), ("ABD", "ABD")],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="etudiant/"),
                ),
            ],
        ),
    ]
